export const GUEST_EXCEL_COLUMNS = [
  { key: "fullName", label: "Full Name", required: true },
  { key: "surname", label: "Surname", required: false },
  { key: "givenName", label: "Given Name", required: false },
  { key: "passportNumber", label: "Passport Number", required: false },
  { key: "idNumber", label: "ID Number", required: false },
  { key: "nationality", label: "Nationality", required: false },
  { key: "dateOfBirth", label: "Date of Birth", required: false },
  { key: "gender", label: "Gender", required: false },
  { key: "passportExpiryDate", label: "Passport Expiry Date", required: false },
  { key: "idExpiryDate", label: "ID Expiry Date", required: false },
  { key: "issuingCountry", label: "Issuing Country", required: false },
  { key: "issuingAuthority", label: "Issuing Authority", required: false },
  { key: "documentType", label: "Document Type", required: true },
  { key: "roomNumber", label: "Room Number", required: false },
  { key: "arrivalDate", label: "Arrival Date", required: false },
  { key: "departureDate", label: "Departure Date", required: false },
  { key: "reservationCode", label: "Reservation Code", required: false },
  { key: "status", label: "Status", required: false },
  { key: "confidenceScore", label: "Confidence Score", required: false },
  { key: "confidenceLevel", label: "Confidence Level", required: false },
  { key: "note", label: "Note", required: false },
  { key: "ocrWarning", label: "OCR Warning", required: false },
  { key: "sourceFile", label: "Source File", required: false },
] as const;
