"""Shared constants for the OCR worker."""

SUPPORTED_IMAGE_EXTENSIONS: set[str] = {
    ".jpg",
    ".jpeg",
    ".png",
    ".tiff",
    ".tif",
    ".bmp",
    ".webp",
}

SUPPORTED_FILE_EXTENSIONS: set[str] = SUPPORTED_IMAGE_EXTENSIONS | {".pdf"}

DEFAULT_LANGUAGE = "eng"
OCR_TIMEOUT_SECONDS = 300

STATUS_READY = "READY"
STATUS_NEED_REVIEW = "NEED_REVIEW"
STATUS_FAILED = "FAILED"
STATUS_FILLED = "FILLED"
STATUS_SKIPPED = "SKIPPED"

CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"

DOC_TYPE_PASSPORT = "PASSPORT"
DOC_TYPE_ID_CARD = "ID_CARD"
DOC_TYPE_UNKNOWN = "UNKNOWN"

GENDER_MALE = "M"
GENDER_FEMALE = "F"
GENDER_UNKNOWN = "UNKNOWN"

DOCUMENT_MODES = ["auto", "passport_mrz", "passport_visual", "id_card", "generic_document"]

WARNING_CODES = {
    "MRZ_NOT_FOUND": "MRZ_NOT_FOUND",
    "MRZ_LINE_INVALID_LENGTH": "MRZ_LINE_INVALID_LENGTH",
    "MRZ_LINE_REPAIRED": "MRZ_LINE_REPAIRED",
    "MRZ_PARSE_FAILED": "MRZ_PARSE_FAILED",
    "MRZ_REPAIRED": "MRZ_REPAIRED",
    "CHECK_DIGIT_FAILED": "CHECK_DIGIT_FAILED",
    "PASSPORT_NUMBER_CHECK_FAILED": "PASSPORT_NUMBER_CHECK_FAILED",
    "DOB_CHECK_FAILED": "DOB_CHECK_FAILED",
    "EXPIRY_CHECK_FAILED": "EXPIRY_CHECK_FAILED",
    "FINAL_CHECK_FAILED": "FINAL_CHECK_FAILED",
    "PASSPORT_NUMBER_MISSING": "PASSPORT_NUMBER_MISSING",
    "ID_NUMBER_MISSING": "ID_NUMBER_MISSING",
    "FULL_NAME_MISSING": "FULL_NAME_MISSING",
    "DOB_MISSING": "DOB_MISSING",
    "EXPIRY_DATE_MISSING": "EXPIRY_DATE_MISSING",
    "GENDER_UNKNOWN": "GENDER_UNKNOWN",
    "EXPIRY_DATE_EXPIRED": "EXPIRY_DATE_EXPIRED",
    "EXPIRY_DATE_SOON": "EXPIRY_DATE_SOON",
    "LOW_CONFIDENCE": "LOW_CONFIDENCE",
    "LOW_IMAGE_SHARPNESS": "LOW_IMAGE_SHARPNESS",
    "IMAGE_TOO_DARK": "IMAGE_TOO_DARK",
    "IMAGE_TOO_BRIGHT": "IMAGE_TOO_BRIGHT",
    "LOW_CONTRAST": "LOW_CONTRAST",
    "IMAGE_SKEWED": "IMAGE_SKEWED",
    "DOCUMENT_PARTIALLY_CUT": "DOCUMENT_PARTIALLY_CUT",
    "GLARE_DETECTED": "GLARE_DETECTED",
    "LOW_RESOLUTION": "LOW_RESOLUTION",
    "IMAGE_LOAD_FAILED": "IMAGE_LOAD_FAILED",
    "IMAGE_UNREADABLE": "IMAGE_UNREADABLE",
    "OCR_TIMEOUT": "OCR_TIMEOUT",
    "OCR_FAILED": "OCR_FAILED",
    "DOCUMENT_TYPE_UNKNOWN": "DOCUMENT_TYPE_UNKNOWN",
    "DOCUMENT_TYPE_UNSUPPORTED": "DOCUMENT_TYPE_UNSUPPORTED",
    "VISUAL_OCR_USED": "VISUAL_OCR_USED",
    "QR_BARCODE_NOT_FOUND": "QR_BARCODE_NOT_FOUND",
    "QR_BARCODE_READ_FAILED": "QR_BARCODE_READ_FAILED",
    "DATA_CONFLICT": "DATA_CONFLICT",
    "PDF_RENDER_FAILED": "PDF_RENDER_FAILED",
    "ONLINE_FALLBACK_USED": "ONLINE_FALLBACK_USED",
    "ONLINE_FALLBACK_FAILED": "ONLINE_FALLBACK_FAILED",
}
